### ISSUE TITLE
Question: How to cite?

### ISSUE THREAD

**Issue by Rhinogradentia** [tsaari88/FeatureSequence#12]
Hi there,

I would like to use your plugin and reference it in a publication. How should I cite?

Best Regards,
Nadine

**Comment by twsaari** [comment]
Hi Nadine, 

Thanks for using the plugin, I'm glad it's useful to you. I don't have any publication associated with it currently (I've actually never thought of that), but if you're able to cite the URL it's definitely appreciated! Something like this would be fine:

Saari TW. 2016. FeatureSequence Plugin. [Cited 2017 November 22]. Available from: www.github.com/tsaari88/FeatureSequence

**Comment by Rhinogradentia** [comment]
Hi,

thank you! 

Best Regards,
Nadine
