### ISSUE TITLE
Notice: name index must be generated before using the plugin

### ISSUE THREAD

**Issue by tao-bioinfo** [tsaari88/FeatureSequence#2]
I've found that if the name index (generated by `generate-names.pl`) is absent, this plugin could not be used. (I use indexed fasta as reference sequence). Currently no manual documents mentioned this.

**Comment by twsaari** [comment]
Thanks for the bug notice. I've not been able to replicate this problem. Any insights from the console? Do you at least get the following text? 

```
FeatureSequence plugin initialized.
```

Edit for clarification: The above text should appear when JBrowse first loads, and this indicates that the plugin was found and the main module was loaded.

Hope to get this resolved for you.

-T
