### ISSUE TITLE
plugin side effect

### ISSUE THREAD

**Issue by keiranmraine** [tsaari88/FeatureSequence#6]
Hi,

I recently released some code to simplify [capturing screen shots from JBrowse](https://github.com/cancerit/cgpJBrowseToolkit#jbrowse_rasterizejs) and while testing found that including the FeatureSequence plugin had an odd interaction with the casperjs/phantomjs framework.

What I discovered was that unless FeatureSequence was the last plugin in the plugin configuration the rendering of the page failed.  Use within a browser seems fine with no apparent errors though.

**Comment by twsaari** [comment]
I think this is probably the same problem that's mentioned in issue #7. There was an open parenthesis in a comment string that I think was causing problems. If this is the problem, then applying the following patch should fix it. I've also gone ahead and made this change on both branches. 

```
diff --git a/js/main.js b/js/main.js
index b9c6630..053eab4 100644
--- a/js/main.js
+++ b/js/main.js
@@ -444,7 +444,7 @@ return declare( JBrowsePlugin,
      * Title: _cleanOverlaps
      * Description: Cleans up commonly found overlapping features by following
      * GFF3 specifications as of July 2016:
-     * (https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md 
+     * https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md 
      * This removes exon features redundant with CDS features, or in cases where exon
      * and CDS coordinates differ, creates implied non-overlapping UTR's
      * @param {overlaps(Array), allFeatures(Array)}
```
