### ISSUE TITLE
This plugin has bugs in IE

### ISSUE THREAD

**Issue by tao-bioinfo** [tsaari88/FeatureSequence#7]
(1) Unless I load the plugin in the last plugin sets, the whole JBrowse failed in IE. The console says:

```
main.js (83,22) lacks ":"
```

(2) If I load the plugin in the last plugin sets, the JBrowse instance is OK in IE, however the plugin itself is still doesn't work in IE

**Comment by twsaari** [comment]
See the answer in #6, I think these errors are caused by the same line.

**Comment by tao-bioinfo** [comment]
Well, after I fix it, it still doesn't work in IE. `main.js (83,22)`:

```
 _prepareAndLaunch(track, feature){

        var self = this; //fix scoping problem with checkForOverlap within async call
```

**Comment by twsaari** [comment]
Ah I see, I bet it's just how the function is defined. Try this:

```
diff --git a/js/main.js b/js/main.js
index 7589f7e..f960aea 100644
--- a/js/main.js
+++ b/js/main.js
@@ -80,7 +80,7 @@ return declare( JBrowsePlugin,
      * @param {track (jbrowse object), feature (jbrowse object)}
      * @returns {  }
      */
-    _prepareAndLaunch(track, feature){
+    _prepareAndLaunch: function(track, feature){

         var self = this; //fix scoping problem with checkForOverlap within async call
```

Once again, I've also made changes to both branches.

**Comment by tao-bioinfo** [comment]
Thanks, Now it works in IE
