### ISSUE TITLE
Not suitable for GFF3Tabix

### ISSUE THREAD

**Issue by tao-bioinfo** [tsaari88/FeatureSequence#9]
JBrowse 1.12.3 has been released and now it supports GFF3Tabix as features. However this plugin seems not usable if we load GFF3Tabix as the features store

**Comment by twsaari** [comment]
I have not used GFF3 Tabix, so I'm not too familiar. It is probably due to [Issue #780 of JBrowse noting the limitations of GFF3Tabix at this time](https://github.com/GMOD/jbrowse/issues/780). This plugin also needs complete information about exons in order to work properly.

**Comment by cmdcolin** [comment]
Recent versions of JBrowse should have complete information about genes with the #780 concerns being fixed :)

**Comment by FredericBGA** [comment]
Using JBrowse 1.16.4 we can't make this plugin working with `GFF3Tabix` features. It works well on `NCList` features.
I can see that in web console:

> TypeError: "e.store.args is undefined"
